name: omg site
favicon: null
layout_spectrum: 0.98247
typography_spectrum: 0.3567428537644446
title: omg site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.9802233024965972
  saturation: 0.54011404607445
  rhythmicContrast: 0.32533213356509805
purpose: []
